name: ADUXX-DCREWARD
version: '1.3'
main: dev.aduxx.aDUXXDCREWARD.DiscordRewardPlugin
author: Aduxx
description: Plugin na nagrode discord
api-version: '1.21'
commands:
  nagroda:
    aliases: [reward]
